# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they have a “cow”.
# For every digit the user guessed correctly in the wrong place is a “bull.”
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
# Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull

from random import randint


def generate_number():
    return str(randint(1000, 9999))


cows = 0
bulls = 0

generated_number = generate_number()
while True:
    user_input = str(input("What is your guess? (1000 to 9999):"))
    if user_input != generated_number:
        for i in range(0, 4):
            if user_input[i] != generated_number[i]:
                cows += 1
            else:
                bulls += 1
        print("You got " + str(bulls) + " bulls and " + str(cows) + " cows.")
    else:
        print("You guessed the number!")
        break
